// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx8xwSgydSFR_vfyc9ASp78WH1xm-Zf6g',
    appId: '1:308284293339:web:74ad1d4b92f449d1a54cfe',
    messagingSenderId: '308284293339',
    projectId: 'sawago-41824',
    authDomain: 'sawago-41824.firebaseapp.com',
    storageBucket: 'sawago-41824.firebasestorage.app',
    measurementId: 'G-5LX16LHGCQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAgndF8d7FDiu2HJBujQLXyAHJ-fNS1Yk',
    appId: '1:308284293339:android:c439356b82002c8da54cfe',
    messagingSenderId: '308284293339',
    projectId: 'sawago-41824',
    storageBucket: 'sawago-41824.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu3BGFarho80gI7c0lWP-TX_Zp95sgkzs',
    appId: '1:308284293339:ios:b2bfe27bc5f707aea54cfe',
    messagingSenderId: '308284293339',
    projectId: 'sawago-41824',
    storageBucket: 'sawago-41824.firebasestorage.app',
    iosClientId: '308284293339-viu2k6okgkserduu87bqdik4ute0rjhd.apps.googleusercontent.com',
    iosBundleId: 'com.example.sawago',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu3BGFarho80gI7c0lWP-TX_Zp95sgkzs',
    appId: '1:308284293339:ios:b2bfe27bc5f707aea54cfe',
    messagingSenderId: '308284293339',
    projectId: 'sawago-41824',
    storageBucket: 'sawago-41824.firebasestorage.app',
    iosClientId: '308284293339-viu2k6okgkserduu87bqdik4ute0rjhd.apps.googleusercontent.com',
    iosBundleId: 'com.example.sawago',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDx8xwSgydSFR_vfyc9ASp78WH1xm-Zf6g',
    appId: '1:308284293339:web:099c6bec6398347fa54cfe',
    messagingSenderId: '308284293339',
    projectId: 'sawago-41824',
    authDomain: 'sawago-41824.firebaseapp.com',
    storageBucket: 'sawago-41824.firebasestorage.app',
    measurementId: 'G-EL9DMB3MGQ',
  );
}
